name: audio-classify
channels:
  - conda-forge
dependencies:
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - numpy=2.3.1
  - scipy=1.16.0
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - librosa=0.11.0
  - joblib=1.5.2
  - python=3.11.14
  - tqdm=4.67.1